//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSP.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSP.Core.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to role failed.
        /// </summary>
        public static string AddToRoleFailed {
            get {
                return ResourceManager.GetString("AddToRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find or create user.
        /// </summary>
        public static string CannotFindOrCreateUser {
            get {
                return ResourceManager.GetString("CannotFindOrCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ARE the virtual assistant for Home Service Platform.
        ///    ## Role and Rules:
        ///    1.  **Proactive Greeting:** Start the conversation with a greeting and **immediately list the services** you can book, e.g., &quot;Hello! I can help you book: 1. Cleaning, 2. Electrical... Which service do you need?&quot;
        ///    2.  **Gather Information:** After that, your ONLY role is to collect 3 pieces of information: `Address`, `DesireDateTime` (Time), and `ServiceIds` (Services).
        ///    3.  **Flexible Time Handling (VERY IMPORTANT):**
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChatbotSystemPrompt {
            get {
                return ResourceManager.GetString("ChatbotSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new service request (booking) for the user. Only call this when you have ALL 3 pieces of info: Address, DesireDateTime, and ServiceIds..
        /// </summary>
        public static string ChatbotToolDescription {
            get {
                return ResourceManager.GetString("ChatbotToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Confirm password field is required.
        /// </summary>
        public static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect.
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exist.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is required.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found from provider.
        /// </summary>
        public static string EmailNotFoundFromProvider {
            get {
                return ResourceManager.GetString("EmailNotFoundFromProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email or Phone Number field is required.
        /// </summary>
        public static string EmailOrPhoneIsRequired {
            get {
                return ResourceManager.GetString("EmailOrPhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading google login.
        /// </summary>
        public static string ErrorLoadingGoogleLogin {
            get {
                return ResourceManager.GetString("ErrorLoadingGoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ExperienceYears field is required.
        /// </summary>
        public static string ExperienceYearsIsRequired {
            get {
                return ResourceManager.GetString("ExperienceYearsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience years must be between 0 and 50.
        /// </summary>
        public static string ExperienceYearsRange {
            get {
                return ResourceManager.GetString("ExperienceYearsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Full name field is required.
        /// </summary>
        public static string FullNameIsRequired {
            get {
                return ResourceManager.GetString("FullNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name must not exceed 100 characters.
        /// </summary>
        public static string FullNameMaxLength {
            get {
                return ResourceManager.GetString("FullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google link failed.
        /// </summary>
        public static string GoogleLinkFailed {
            get {
                return ResourceManager.GetString("GoogleLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be null.
        /// </summary>
        public static string InputCannotBeNull {
            get {
                return ResourceManager.GetString("InputCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is not a valid email address.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number format.
        /// </summary>
        public static string InvalidPhoneNumberFormat {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available technician found .
        /// </summary>
        public static string NoAvailableTechniciansFound {
            get {
                return ResourceManager.GetString("NoAvailableTechniciansFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change failed.
        /// </summary>
        public static string PasswordChangeFailed {
            get {
                return ResourceManager.GetString("PasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 and at max 100 characters long.
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password do not match.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone Number field is required.
        /// </summary>
        public static string PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number cannot exceed 20 characters.
        /// </summary>
        public static string PhoneNumberMaxLength {
            get {
                return ResourceManager.GetString("PhoneNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email for password reset instructions.
        /// </summary>
        public static string Pleasecheckyouremailforpasswordresetinstructions {
            get {
                return ResourceManager.GetString("Pleasecheckyouremailforpasswordresetinstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SkillSet field is required.
        /// </summary>
        public static string SkillSetIsRequired {
            get {
                return ResourceManager.GetString("SkillSetIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creation failed.
        /// </summary>
        public static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exist.
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
