name: Dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore HomeServicePlatform.sln

    - name: Build project
      run: dotnet build --configuration Debug --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
