name: Dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore HomeServicePlatform.sln
      working-directory: HomeServicePlatform

    - name: Build project
      run: dotnet build HomeServicePlatform.sln --configuration Debug --no-restore
      working-directory: HomeServicePlatform

    - name: Run tests
      run: dotnet test HomeServicePlatform.sln --no-build --verbosity normal
      working-directory: HomeServicePlatform
